version: "3.9"
services:
  db:
    image: postgres:13.3
    container_name: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
