// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'bgAuthum': string;
  'bgSpring': string;
  'bgSummer': string;
  'bgWinter': string;
  'inp': string;
}
export const cssExports: CssExports;
export default cssExports;
