// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form_radio_group': string;
  'form_radio_group-item': string;
}
export const cssExports: CssExports;
export default cssExports;
