// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'menu': string;
  'toggle': string;
  'wraper': string;
}
export const cssExports: CssExports;
export default cssExports;
