// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkedCell': string;
  'colHeader': string;
  'hoverTr': string;
  'inputChexkBox': string;
  'loadSpinner': string;
  'rotated270': string;
  'rotated90': string;
  'selectExpand': string;
  'selectRow': string;
  'table': string;
  'tableRow': string;
}
export const cssExports: CssExports;
export default cssExports;
