name: test on enviroment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build:server

      - name: Lint
        run: |
          yarn lint:server

      - name: Prepare test enviroment
        run: |
          yarn env:up

      - name: Running tests
        run: |
          yarn test
